name: Publish Wootbot Docker images

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker Tag
        id: set_docker_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "DOCKER_TAG=conlab/wootbot:latest" >> $GITHUB_ENV
          else
            REF_NAME=$(echo "${{ github.ref }}" | sed -e 's@refs/tags/@@') 
            echo "DOCKER_TAG=conlab/wootbot:$REF_NAME" >> $GITHUB_ENV
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_TAG }}
